-- Learning experience fields used by the learning API.
create table if not exists public.learning_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  article_id bigint not null,
  status text not null default 'read',
  created_at timestamptz not null default now()
);

alter table if exists public.learning_records
  add column if not exists comprehension_level integer check (comprehension_level between 1 and 5),
  add column if not exists memo text,
  add column if not exists practical_task_done boolean not null default false,
  add column if not exists next_review_at timestamptz;

create table if not exists public.learning_quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  article_id bigint not null,
  score integer not null check (score >= 0),
  total integer not null check (total > 0),
  created_at timestamptz not null default now()
);

create index if not exists learning_quiz_attempts_user_id_idx
  on public.learning_quiz_attempts (user_id, created_at desc);
create index if not exists learning_records_review_idx
  on public.learning_records (user_id, next_review_at);
