-- Unified learning resources for articles, videos, books, repositories, and courses.
create table if not exists public.learning_resources (
  id bigint generated by default as identity primary key,
  resource_type text not null check (resource_type in ('article', 'video', 'book', 'repository', 'course')),
  external_id text not null,
  title text not null,
  summary text,
  url text not null,
  thumbnail_url text,
  source text not null,
  topic text,
  difficulty text check (difficulty in ('beginner', 'intermediate', 'advanced')),
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (resource_type, external_id),
  unique (url)
);

create index if not exists learning_resources_type_topic_idx
  on public.learning_resources (resource_type, topic);
create index if not exists learning_resources_created_at_idx
  on public.learning_resources (created_at desc);

comment on table public.learning_resources is 'Unified catalog of learning content from external providers';
comment on column public.learning_resources.external_id is 'Stable provider ID, such as a YouTube video ID or GitHub repository URL';
