-- Per-user progress for non-article learning resources.
create table if not exists public.resource_learning_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  resource_id bigint not null references public.learning_resources(id) on delete cascade,
  status text not null default 'started' check (status in ('started', 'completed')),
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, resource_id)
);

create index if not exists resource_learning_records_user_idx
  on public.resource_learning_records (user_id, updated_at desc);
